# PROVA DE MACHINE LEARNING

In [11]:
import pandas as pd

df = pd.read_csv('class01.csv')

df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x91,x92,x93,x94,x95,x96,x97,x98,x99,target
0,1.162990,-0.831971,-0.185266,0.441240,0.033957,1.432988,-1.171483,0.203248,1.900889,1.119174,...,-1.139286,-0.608239,-0.107224,1.700972,-0.698151,0.520004,-0.450784,-0.187694,-0.538329,1.0
1,-1.750976,-0.516614,-0.761588,1.692347,-1.579436,0.581782,-0.950953,0.381426,-1.370027,0.943387,...,-0.280502,-0.306014,0.554926,-1.402866,-0.776478,1.181890,-0.066449,-0.802430,1.587229,0.0
2,0.304635,0.972369,0.202908,-0.607761,0.487088,0.205173,0.815216,0.491880,0.904705,1.167017,...,-0.134901,0.291496,-1.038477,1.297057,-1.296614,-1.109806,-0.003495,-0.149940,0.539892,8.0
3,-1.667576,-0.262639,-1.513473,-1.060125,-0.456209,1.782235,1.034366,0.115217,-0.182177,-1.007720,...,1.203067,0.082647,-1.625862,-0.154116,0.478483,-1.465050,-0.450510,-0.757631,-3.184493,7.0
4,-0.820670,0.390631,0.761628,-0.945407,-0.871003,-0.142293,-1.522004,0.141962,0.091094,-0.860818,...,1.955541,0.079445,0.528177,1.522003,1.849394,-1.194590,1.023761,-0.335391,2.448868,3.0

In [ ]:
X = df.drop(columns=['target'])
X.head()

In [4]:
X.shape

(1000, 100)

In [5]:
y = df['target']
y.head()

0    1.0
1    0.0
2    8.0
3    7.0
4    3.0
Name: target, dtype: float64

# NAIVE BAYES GAUSSIANO

In [12]:
X_train = X[:350]
y_train = y[:350]

X_test = X[350:]
y_test = y[350:]

In [13]:
from sklearn.naive_bayes import GaussianNB

In [18]:

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
from sklearn.metrics import accuracy_score

In [19]:
# acuracia do treino
y_true = y_train
y_pred = model.predict(X_train)

accuracy_score(y_true, y_pred)

0.76

In [20]:
# utilizando o score

model.score(X_train, y_train)

0.76

In [21]:
# acuracia pra validacao (teste)
model.score(X_test, y_test)

0.6276923076923077

# Leave One Out

In [37]:
from sklearn.model_selection import LeaveOneOut

my_cv = LeaveOneOut()
scores_train = []
scores_test = []


for train_index, test_index in my_cv.split(X):
    
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    
    y_train = y.iloc[train_index]
    y_test = y.iloc[test_index]
    
    model = GaussianNB()
    model.fit(X_train, y_train)
    
    scores_train.append(model.score(X_train, y_train))
    scores_test.append(model.score(X_test, y_test))

In [39]:
import numpy as np

In [40]:
print(np.mean(scores_train))
print(np.mean(scores_test))

0.6892802802802803
0.642

In [44]:
from sklearn.model_selection import cross_val_score, cross_validate

In [46]:
np.mean(cross_val_score(GaussianNB(), X, y, cv=LeaveOneOut()))

0.642

In [49]:
results = cross_validate(GaussianNB(), X, y, cv=LeaveOneOut(), return_train_score=True)
print(np.mean(results['train_score']))
print(np.mean(results['test_score']))

0.6892802802802803
0.642

# Exercicio 3

In [78]:
df = pd.read_csv('class02.csv')
X = df.drop(columns=['target'])
y = df['target']

In [79]:
from sklearn.neighbors import KNeighborsClassifier

In [80]:
from sklearn.model_selection import KFold

In [81]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler().fit(X)

In [82]:
X_std = scalar.transform(X)

In [83]:
X.describe()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x90,x91,x92,x93,x94,x95,x96,x97,x98,x99
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,...,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,0.008314,0.009800,0.007239,-0.018379,-0.017845,-0.021501,0.076072,0.683646,0.014536,-0.330924,...,-0.883332,0.006340,-0.029977,0.539687,0.474653,0.213493,-0.274812,-0.029580,-0.006974,-0.019899
std,1.030753,1.008097,0.986173,0.992657,1.027257,0.984912,0.992942,1.406161,1.042316,1.758336,...,1.747692,0.963779,1.031497,2.052363,1.645052,1.909870,2.807689,1.006713,1.012434,1.029865
min,-3.384578,-3.249925,-2.975763,-3.703641,-3.531879,-3.532532,-3.028050,-3.534037,-3.329805,-5.420413,...,-7.008398,-3.254561,-3.472939,-7.398384,-5.318167,-5.799053,-10.734047,-3.731865,-3.441579,-3.601807
25%,-0.688747,-0.646271,-0.700442,-0.697381,-0.732945,-0.692937,-0.600687,-0.248680,-0.701506,-1.374344,...,-2.010453,-0.677411,-0.699784,-0.886487,-0.613217,-1.037239,-2.037693,-0.717395,-0.688855,-0.735033
50%,0.037292,0.022439,-0.012963,0.013802,-0.019798,-0.008975,0.061965,0.721283,0.022580,-0.329807,...,-0.959705,0.029871,-0.027605,0.357904,0.370950,0.203571,-0.394867,-0.040162,0.013708,-0.040961
75%,0.709844,0.683747,0.670708,0.649219,0.670900,0.628271,0.740672,1.620969,0.737117,0.898264,...,0.252399,0.677443,0.675564,1.804786,1.550150,1.479166,1.608777,0.618818,0.700447,0.693127
max,3.544065,3.058110,3.789975,3.271020,2.740552,2.785632,3.443926,5.113613,3.167190,4.533001,...,4.271384,3.292169,4.298858,8.221332,6.415407,6.004815,7.575307,2.902942,3.052001,3.553621

In [84]:
pd.DataFrame(X_std)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1.694085,-1.283645,-0.488591,-0.312522,1.149651,1.149315,-0.613377,0.254892,0.363839,1.046689,...,-0.803882,-0.113096,0.255656,-1.097304,0.207759,1.302617,1.100265,0.370607,0.351456,-0.242688
1,0.553979,0.486123,1.867619,-2.034901,-0.460516,-0.866838,0.918964,-0.402970,0.601561,0.780685,...,-0.095339,-0.124612,0.919951,0.327890,1.252867,-0.999358,-0.799596,0.557089,-0.417896,-0.984657
2,3.345579,-0.846821,-1.204554,-1.381192,-0.726483,-0.800634,-0.303365,0.096139,0.966072,-0.088643,...,-0.368021,-0.849570,-0.628404,0.977491,1.066541,-1.112897,-1.314980,1.314201,0.200922,-0.699280
3,2.822876,-1.368406,1.324194,-0.430107,0.229754,2.043027,-1.262062,-0.569412,1.178444,0.245597,...,-0.015779,-1.762447,-1.817272,-0.476465,-0.618378,0.466727,-0.305557,0.606232,0.948535,1.615478
4,1.511032,-0.081185,1.274474,0.952636,-1.705792,0.779245,0.907669,1.649905,1.758827,-0.456123,...,-2.037755,0.157521,3.512550,0.646669,0.885501,0.794910,-0.332111,-0.921252,-0.332492,1.180002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,-0.476883,-0.789032,-1.502420,-0.348399,0.777720,-1.386064,-0.342245,-0.698467,-1.133380,0.358766,...,1.465985,0.038315,2.068197,-0.930269,-0.852472,-0.016835,1.379622,-0.359767,0.062162,-1.406753
1496,0.678429,-0.148292,-1.891332,-0.053674,0.120720,-1.806534,-1.932383,-1.091562,0.223296,1.240727,...,-1.729526,-0.717527,-0.143741,-1.444224,-1.080969,1.816309,-1.790377,1.061544,1.074349,-0.138426
1497,-0.945457,0.356535,1.071651,0.930805,-1.495246,-0.633880,-1.765483,0.368779,-0.795195,0.172183,...,-1.526325,-0.963635,-1.140707,-0.828351,-0.815566,1.893862,-0.148613,-1.824222,-0.270718,0.466470
1498,-0.281204,-0.117652,0.125374,-0.626386,-1.650876,1.162325,1.484254,-0.150056,-1.836134,0.102714,...,-0.302828,0.284642,0.767766,-0.767715,-0.940853,1.246647,0.372127,-1.012833,-0.366299,1.673796
1499,2.860030,0.086512,0.780604,0.147053,0.949797,2.186086,-0.248608,-1.527492,1.969564,0.257358,...,2.143530,-0.112571,1.037881,0.769726,0.734588,-2.361417,-0.586620,1.703830,-0.484616,0.959424

In [85]:
X_std = scalar.transform(X)

results = cross_validate(KNeighborsClassifier(n_neighbors=10), 
                         X_std, 
                         y, 
                         cv=KFold(n_splits=10), 
                         return_train_score=True)

print(np.mean(results['test_score']))

0.758

# Regressao

In [86]:
df = pd.read_csv('reg01.csv')
X = df.drop(columns=['target'])
y = df['target']

In [87]:
from sklearn.linear_model import Lasso

In [88]:
lasso = Lasso()
scalar = StandardScaler().fit(X)

In [90]:


results = cross_validate(lasso, 
                         scalar.transform(X), 
                         y, 
                         cv=LeaveOneOut(), 
                         return_train_score=True,
                         scoring='neg_root_mean_squared_error')

print(np.mean(results['train_score']))
print(np.mean(results['test_score']))

-19.219646382953055
-15.461344370827744